//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace NPerf.Framework
{
	using System;
	
	
	/// <summary>
	/// A custom attribute to disable tester or tests
	/// </summary>
	[AttributeUsage(
		AttributeTargets.Class 
		| AttributeTargets.Struct
		| AttributeTargets.Method,
		AllowMultiple=false)
	]
	public class PerfIgnoreAttribute : System.Attribute
	{
		/// <summary>
		/// Default constructor - initializes all fields to default values
		/// </summary>
		public PerfIgnoreAttribute(string message)
		{
			if(message==null)
				throw new ArgumentNullException("message");
            this.Message = message;
		}

	    /// <summary>Gets the reason why the test is ignored</summary>
	    /// <value>Explanation of the test ignore</value>
        public string Message { get; private set; }
	}
}
