//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace NPerf.Core
{
	using System;
	
	
	/// <summary>
	/// TODO - Add class summary
	/// </summary>
	/// <remarks>
	/// 	created by - dehalleux
	/// 	created on - 26/01/2004 13:13:00
	/// </remarks>
	public class PerfTestEventArgs : System.EventArgs
	{
		private PerfTest test;
		
		/// <summary>
		/// Default constructor - initializes all fields to default values
		/// </summary>
		public PerfTestEventArgs(PerfTest test)
		{
			if (test==null)
				throw new ArgumentNullException("test");
			this.test = test;
		}
		
		public PerfTest Test
		{
			get
			{
				return this.test;
			}
		}
	}
	
	public delegate void PerfTestEventHandler(Object sender,PerfTestEventArgs e); 
}
